Update PPP, update sort UG and add tests
AY2122S2-CS2103T-T12-2/tp pull request #195
Opened 2022-04-08 20:57 UTC by tehkokhoe

2022-04-10 11:54 UTC, glennljw requested changes
Nice work on the tests Kok Hoe! I can see the amount of effort put into this piece of work. Thanks for being meticulous in your testing! LGTM, just some minor nits to fix! 😄

2022-04-10 11:54 UTC, glennljw commented on src/main/java/seedu/address/model/person/Deadline.java
> +            return date.before(FORMATTER.parse("01/01/10000"));
For this as well, I'm not sure if it's considered as a feature flaw.

2022-04-10 11:54 UTC, glennljw commented on src/test/java/seedu/address/logic/commands/CommandTestUtil.java
> +     * - thre returned {@link CommandResult} matches {@code expectedCommandResult} <br>
Minor typo here maybe? `thre`

2022-04-10 12:16 UTC, tehkokhoe commented on src/main/java/seedu/address/model/person/Deadline.java
> +        checkArgument(isValidDeadline(description, dateAsString), MESSAGE_CONSTRAINTS);
I think this only affects testing, because normally the valid deadline should have already been checked before it reaches this point.

2022-04-10 12:20 UTC, tehkokhoe commented on docs/UserGuide.md
> +| `CRITERIA` | Comparator                                           |
I will change to "Order"?

2022-04-10 14:05 UTC, glennljw commented on src/main/java/seedu/address/model/person/Deadline.java
> +        checkArgument(isValidDeadline(description, dateAsString), MESSAGE_CONSTRAINTS);
Okay got it!

2022-04-10 14:06 UTC, glennljw commented on docs/UserGuide.md
> +| `CRITERIA` | Comparator                                           |
I think that's nice! 😄

2022-04-11 06:23 UTC, glennljw approved these changes

2022-04-11 06:35 UTC, merged