[DRAFT] Add favourites
AY2122S2-CS2103T-T12-2/tp pull request #37
Opened 2022-03-07 10:53 UTC by takufunkai

TO BE FILLED

2022-03-07 16:21 UTC, weijuey requested changes
LGTM, just a small nit to fix 👍

2022-03-07 16:21 UTC, weijuey commented on src/main/java/seedu/address/model/person/Favourite.java
> +     * Constructs a {@code Phone}.
I think you forgot to change this 😆

2022-03-08 10:27 UTC, takufunkai commented on src/main/java/seedu/address/model/person/Favourite.java
> +     * Constructs a {@code Phone}.
Thanks! Will make the change.

2022-03-08 10:39 UTC, weijuey reviewed
LGTM 👍

2022-03-08 10:40 UTC, weijuey approved these changes

2022-03-08 10:40 UTC, merged